### ISSUE TITLE
argument ts_hspace 

### ISSUE THREAD

**Issue by ALindblomA** [mapattacker/dendrogram-ts#3]
With the new update it says to use the argument "ts_hspace" when calling one of the dendrogram functions ( I am only a beginner programmer so I dont know if those are the correct terms) , however it does not work for me. But the old argument "ts_space" from before the latest update still works.  Don't know why? But I can still run the package with the old argument, so just whanted to let you know :)

Best regards
Anna

**Comment by mapattacker** [comment]
Hi @ALindblomA, which function did u try that only works for `ts_space` and not `ts_hspace`?

**Comment by mapattacker** [comment]
I just tried all 3 functions & `ts_hspace` works. Could it be because you still have the old script in your folder?

**Comment by ALindblomA** [comment]
Hi, yes that might have been the case! I tried running it today with ts_hspace and now it works. Sorry for the confusion :)
